services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile

    container_name: serverhub-api

    ports:
      - "8000:8000"

    restart: unless-stopped

    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:18

    container_name: serverhub-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

volumes:
  postgres_data:
